CREATE TABLE IF NOT EXISTS employee_passport (
    id VARCHAR(50) PRIMARY KEY,
    employee_id VARCHAR(50) NOT NULL REFERENCES employee(id) ON DELETE CASCADE,
    passport_number VARCHAR(50) UNIQUE NOT NULL,
    issue_date DATE NOT NULL,
    expiry_date DATE NOT NULL,
    place_of_issue VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS employee_visa (
    id VARCHAR(50) PRIMARY KEY,
    employee_id VARCHAR(50) NOT NULL REFERENCES employee(id) ON DELETE CASCADE,
    visa_number VARCHAR(50) NOT NULL,
    visa_type VARCHAR(50) NOT NULL,
    expiry_date DATE NOT NULL,
    entry_type VARCHAR(20) DEFAULT 'MULTIPLE' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
